// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cffsbeskawafyspxxsjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZnNiZXNrYXdhZnlzcHh4c2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjI1OTAsImV4cCI6MjA2NDM5ODU5MH0.yW0zT_pj11CosRGnazLF2RtqWc3dZ_bSkQa_o8E91RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);